name: acos-rest16-quad-nl-constrained
model:
  name: google/flan-t5-base
  max_length: 384
  max_new_tokens: 128
  val_batch_size: 32
generation:
  num_beams: 1
  constrained_decoding: true
test:
  scopes:
  - keys:
    - aspect
    - sentiment
    - polarity
    - category
    metrics:
    - micro_f1
  - keys:
    - aspect
    - polarity
    - category
    metrics:
    - micro_f1
  - keys:
    - category
    metrics:
    - micro_f1
    - macro_f1
  - keys:
    - aspect
    metrics:
    - micro_f1
  - keys:
    - polarity
    metrics:
    - micro_f1
    - macro_f1
  - keys:
    - aspect
    - sentiment
    - polarity
    metrics:
    - micro_f1
  datasets:
  - data: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_test.tsv.jsonl
    tasks:
    - aspect
    - sentiment
    - polarity
    - category
  - data: downloads/ABSADatasets/datasets/acos_datasets/501.Laptop14/laptop_quad_test.tsv.jsonl
    tasks:
    - aspect
    - sentiment
    - polarity
    - category
  filter_implicit: false
  eval_implicit_split: true
  implicit_mode: null
  output_format: natural-language
seed: 42
