name: acos-rest16-quad-nl-struct-attn
model:
  name: google/flan-t5-base
  learning_rate: 0.0001
  max_length: 384
  max_new_tokens: 128
  batch_size: 8
  val_batch_size: 32
  label_smoothing: 0.05
generation:
  num_beams: 1
trainer:
  early_stopping_patience: 0
  max_epochs: 30
  precision: bf16-mixed
  accumulate_grad_batches: 2
  strategy: ddp
data:
  train_file: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_train.tsv.jsonl
  filter_implicit: false
  tasks_partition:
    quad: 1.0
  shuffle_tasks: false
  natural_language_fraction: 1.0
  syntax_enrichment: dep-compact
  structured_attention: true
  infer_implicit: false
eval:
  val_split: 0
  data: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_dev.tsv.jsonl
  tasks:
  - aspect
  - sentiment
  - polarity
  - category
  scopes:
  - keys:
    - aspect
    - sentiment
    - polarity
    - category
    metrics:
    - micro_f1
  - keys:
    - aspect
    - polarity
    - category
    metrics:
    - micro_f1
  - keys:
    - category
    metrics:
    - micro_f1
    - macro_f1
  - &id001
    keys:
    - aspect
    - sentiment
    - polarity
    metrics:
    - micro_f1
  output_format: natural-language
test:
  scopes:
  - keys:
    - aspect
    - sentiment
    - polarity
    - category
    metrics:
    - micro_f1
  - keys:
    - aspect
    - polarity
    - category
    metrics:
    - micro_f1
  - keys:
    - category
    metrics:
    - micro_f1
    - macro_f1
  - keys:
    - aspect
    metrics:
    - micro_f1
  - keys:
    - polarity
    metrics:
    - micro_f1
    - macro_f1
  - *id001
  datasets:
  - data: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_test.tsv.jsonl
    tasks:
    - aspect
    - sentiment
    - polarity
    - category
  - data: downloads/ABSADatasets/datasets/acos_datasets/501.Laptop14/laptop_quad_test.tsv.jsonl
    tasks:
    - aspect
    - sentiment
    - polarity
    - category
  filter_implicit: false
  eval_implicit_split: true
  implicit_mode: null
  output_format: natural-language
seed: 42
