name: acos-split-nl30
model:
  name: google/flan-t5-base
trainer:
  max_epochs: 20
data:
  train_file: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_train.tsv.jsonl
  tasks_partition:
    aspect: 0.0625
    sentiment: 0.0625
    polarity: 0.0625
    category: 0.0625
    aspect+sentiment: 0.042
    aspect+polarity: 0.042
    aspect+category: 0.042
    sentiment+polarity: 0.042
    sentiment+category: 0.042
    polarity+category: 0.04
    full: 0.0625
    aspect+sentiment+category: 0.0625
    aspect+polarity+category: 0.0625
    sentiment+polarity+category: 0.0625
    quad: 0.25
  shuffle_tasks: true
  natural_language_fraction: 0.3
eval:
  val_split: 0
  data: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_dev.tsv.jsonl
  tasks: &id002
  - aspect
  - sentiment
  - polarity
  - category
  scopes: &id001
  - keys:
    - aspect
    - sentiment
    - polarity
    - category
    metrics:
    - micro_f1
test:
  scopes: *id001
  datasets:
  - data: downloads/ABSADatasets/datasets/acos_datasets/504.Restaurant16/rest16_quad_test.tsv.jsonl
    tasks: *id002
  - data: downloads/ABSADatasets/datasets/acos_datasets/501.Laptop14/laptop_quad_test.tsv.jsonl
    tasks: *id002
