name: aste-rest15-nl-pos-aux
model:
  name: google/flan-t5-base
  learning_rate: 0.0003
  max_length: 256
  max_new_tokens: 128
  batch_size: 16
  val_batch_size: 32
  label_smoothing: 0.05
generation:
  num_beams: 1
trainer:
  early_stopping_patience: 0
  max_epochs: 30
  precision: bf16-mixed
  accumulate_grad_batches: 2
  strategy: ddp
data:
  train_file: downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/403.Restaurant15/train.txt
  filter_implicit: false
  tasks_partition:
    full: 1.0
  shuffle_tasks: false
  natural_language_fraction: 1.0
  syntax_enrichment: pos-compact
  syntax_auxiliary_fraction: 0.1
  syntax_auxiliary_tasks:
  - pos
eval:
  val_split: 0
  data: downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/403.Restaurant15/dev.txt
  tasks:
  - aspect
  - sentiment
  - polarity
  scopes:
  - keys:
    - aspect
    - sentiment
    - polarity
    metrics:
    - micro_f1
  output_format: natural-language
test:
  scopes:
  - keys:
    - aspect
    - sentiment
    - polarity
    metrics:
    - micro_f1
  datasets:
  - data: downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/403.Restaurant15/test.txt
    tasks:
    - aspect
    - sentiment
    - polarity
  filter_implicit: false
  eval_implicit_split: false
  output_format: natural-language
seed: 42
