name: aste-bare-structured
model:
  name: google/flan-t5-base
  learning_rate: 0.0003
  max_length: 256
  max_new_tokens: 64
  batch_size: 8
  val_batch_size: 32
  label_smoothing: 0.05
generation:
  num_beams: 1
trainer:
  early_stopping_patience: 0
  max_epochs: 30
  precision: bf16-mixed
  accumulate_grad_batches: 2
  strategy: ddp
data:
  train_file:
  - downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/402.Restaurant14/train.txt
  - downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/403.Restaurant15/train.txt
  - downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/404.Restaurant16/train.txt
  tasks_partition:
    full: 1.0
  shuffle_tasks: false
  natural_language_fraction: 0.0
  syntax_enrichment: null
  bare_prompt: true
eval:
  val_split: 0
  data: downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/402.Restaurant14/dev.txt
  tasks: &tasks
  - aspect
  - sentiment
  - polarity
  scopes: &scopes
  - keys:
    - aspect
    - sentiment
    - polarity
    metrics:
    - micro_f1
  output_format: structured
test:
  scopes: *scopes
  datasets:
  - data: downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/402.Restaurant14/test.txt
    tasks: *tasks
  - data: downloads/ABSADatasets/datasets/aste_datasets/400.SemEval/401.Laptop14/test.txt
    tasks: *tasks
  output_format: structured
seed: 42
