name: split-50-50
model:
  name: google/flan-t5-base
data:
  train_file: downloads/silviolima/restaurant.json
  tasks_partition:
    aspect: 0.167
    polarity: 0.166
    sentiment: 0.167
    full: 0.5
  shuffle_tasks: true
  filter_implicit: true
eval:
  val_split: 0.1
test:
  datasets:
  - data: downloads/silviolima/laptop.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/beauty.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/book.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/electronics.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/fashion.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/grocery.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/home.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/pet.json
    tasks:
    - aspect
    - sentiment
    - polarity
  - data: downloads/silviolima/toy.json
    tasks:
    - aspect
    - sentiment
    - polarity
